routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [EmployeeController::class, 'index'])->name('employees.index');
Route::resources([
    'employees' => EmployeeController::class,
]);
Route::get('/getData/employees', [EmployeeController::class, 'getData'])->name('employees.getData');

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    public $table = 'employees';
    protected $fillable = [
        'first_name', 'middle_name', 'last_name', 'other_name', 'work_country', 'document_type', 'document_number', 'email', 'department', 'status', 'start_date'
    ];

    /**
     * Create a new mail address for an employee
     */
    public function generateEmailAddress()
    {
       $emailDomain = $this->work_country == "Estados Unidos" ? 'cidenet.com.us' : 'cidenet.com.co';
       $newMailAddress = trim(strtolower($this->first_name . '.' . $this->middle_name));
       if(!$this->checkMailUniqueness($newMailAddress . '@' . $emailDomain)){
           // This will be always unique because of the ID
           $this->email = $newMailAddress . '.' . $this->id . '@' . $emailDomain;
       }else{
           $this->email = $newMailAddress . '@' . $emailDomain;
       }
        return $this->save();
    }

    /**
     * Check if an email address already exists
     *
     * @param $emailAddress
     * @return bool
     */
    public function checkMailUniqueness($emailAddress)
    {
       if (Employee::where('email', $emailAddress)) {
           return false;
       }
       return true;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class EmployeeController extends Controller
{

    public function index()
    {
        return view('employees.index');
    }

    public function getData()
    {
        $data = Employee::orderBy('id', 'desc')->get();
        return Datatables::of($data)->make(true);
    }

    public function create()
    {
        return view('employees.modal-create')->render();
    }

    public function store(Request $request)
    {
        $request->validate([
            'first_name' => ['bail', 'required', 'max:20', 'regex:/^[a-zA-Z]+$/u'],
            'middle_name' => ['bail', 'required', 'max:20', 'regex:/^[a-zA-Z]+$/u'],
            'last_name' => ['bail', 'required', 'max:20', 'regex:/^[a-zA-Z]+$/u'],
            'other_name' => ['bail', 'max:50', 'regex:/^[a-zA-Z\s]+$/u'],
            'work_country' => ['bail', 'required'],
            'document_type' => ['bail', 'required', 'max:20'],
            'document_number' => ['bail', 'required', 'max:20', 'unique:employees'],
            'department' => ['bail', 'required'],
            'start_date' => ['bail', 'required', 'before_or_equal:today', 'after_or_equal:' . Carbon::now()->subMonth()->format('Y-m-d')]
        ]);

        $newEmployee = new Employee([
            'first_name' => strtoupper($request->first_name),
            'middle_name' => strtoupper($request->middle_name),
            'last_name' => strtoupper($request->last_name),
            'other_name' => strtoupper($request->other_name),
            'work_country' => $request->work_country,
            'document_type' => $request->document_type,
            'document_number' => $request->document_number,
            'department' => $request->department,
            'start_date' => $request->start_date,
            'status' => 'Active',
        ]);

        try {
            if ($newEmployee->save()) {
                return json_encode([
                    'success' => $newEmployee->generateEmailAddress()
                ]);
            }
        } catch (\Exception $error) {
            throw $error;
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Employee $employee
     */
    public function edit(Employee $employee)
    {
        return view('employees.modal-create', ['employee' => $employee])->render();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Employee $employee
     */
    public function update(Request $request, Employee $employee)
    {
        $request->validate([
            'first_name' => ['bail', 'required', 'max:20', 'regex:/^[a-zA-Z]+$/u'],
            'middle_name' => ['bail', 'required', 'max:20', 'regex:/^[a-zA-Z]+$/u'],
            'last_name' => ['bail', 'required', 'max:20', 'regex:/^[a-zA-Z]+$/u'],
            'other_name' => ['bail', 'max:50', 'regex:/^[a-zA-Z\s]+$/u'],
            'work_country' => ['bail', 'required'],
            'document_type' => ['bail', 'required', 'max:20'],
            'document_number' => ['bail', 'required', 'max:20', 'unique:employees,document_number,' . $employee->id],
            'department' => ['bail', 'required'],
            'start_date' => ['bail', 'required', 'before_or_equal:today', 'after_or_equal:' . Carbon::now()->subMonth()->format('Y-m-d')]
        ]);

        $employee->first_name = $request->first_name;
        $employee->middle_name = $request->middle_name;
        $employee->last_name = $request->last_name;
        $employee->other_name = $request->other_name;
        $employee->work_country = $request->work_country;
        $employee->document_type = $request->document_type;
        $employee->document_number = $request->document_number;
        $employee->department = $request->department;
        $employee->start_date = $request->start_date;
        $employee->status = 'Active';

        try {
            if ($employee->save()) {
                $employee->generateEmailAddress();
                return json_encode([
                    'success' => $employee->generateEmailAddress()
                ]);
            }
        } catch (\Exception $error) {
            throw $error;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Employee $Employee
     */
    public function destroy(Employee $Employee)
    {
        $Employee->delete();
        return response()->json('Deleted succesefully');
    }
}

resources/views/employees/index.blade.php
@extends('layouts.app')
@section('content')
    <nav class="navbar">
        <form class="container-fluid justify-content-start px-0">
            <button class="btn btn-outline-success me-2"
                    data-bs-toggle="modal"
                    data-bs-target="#modalWrapper"
                    data-content-source="{!! route('employees.create') !!}"
                    type="button"><i class="bi bi-person-plus-fill"></i>&nbsp; {{ __('general.new') }}
            </button>
        </form>
    </nav>
    <div class="mt-3 ">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped w-100" id="employeesTable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>First Name</th>
                            <th>Middle name</th>
                            <th>Last name</th>
                            <th>Other name</th>
                            <th>Work country</th>
                            <th>Document type</th>
                            <th>Document number</th>
                            <th>E-mail</th>
                            <th>Status</th>
                            <th>Option</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @csrf
    @php $route = 'employees.getData'; @endphp
    <script>
        window.addEventListener('DOMContentLoaded', event => {
            $('#employeesTable').DataTable({
                "processing": true,
                "order": [[0, "desc"]],
                responsive: true,
                "serverSide": true,
                ajax: "{{route($route)}}",
                // "sAjaxDataProp": "",
                columns: [
                    {"data": "id"},
                    {"data": "first_name"},
                    {"data": "middle_name"},
                    {"data": "last_name"},
                    {"data": "other_name"},
                    {"data": "work_country"},
                    {"data": "document_type"},
                    {"data": "document_number"},
                    {"data": "email"},
                    {"data": "status"},
                    {
                        "data": "id",
                        title: '{{ __('general.options') }}',
                        wrap: true,
                        "render": function (data, type, row, meta) {
                            return `
                                <div class="btn-group me-2" role="group" id="action-buttons">
                                   <button class="btn btn-sm btn-primary"
                                        data-bs-toggle="modal"
                                        data-bs-target="#modalWrapper"
                                        data-content-source="/employees/${row['id']}/edit">
                                        <i class="fas fa-user-edit"></i>
                                   </button>
                                   <button class="btn btn-sm btn-danger delete-entry"
                                        data-action-route="/employees/${row['id']}"
                                        data-entry-id="${row['id']}">
                                        <i class="fas fa-trash-alt"></i>
                                   </button>
                               </div>
                            `;
                        }
                    }
                ],
            });

            /*
            * Delete elements
            * */

            $("body").on("click", ".delete-entry", (event) => {
                let clickedButton = event.currentTarget;
                let callURL = clickedButton.getAttribute('data-action-route');
                let entryId = clickedButton.getAttribute('data-entry-id');
                swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover the data!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                }).then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url: callURL,
                            data: {
                                "_token": $("meta[name='csrf-token']").attr("content"),
                                id: entryId
                            },
                            method: 'DELETE',
                            success: () => {
                                swal("The data has been deleted!", {
                                    icon: "success",
                                });
                                $('#employeesTable').DataTable().ajax.reload();
                            },
                            error: () => {
                                swal("There was an error deleting the data. Please try again!", {
                                    icon: "error",
                                });
                            }
                        });
                    }
                });
            });

        });
    </script>
@endsection

resources/views/employees/modal-create.blade.php
<div class="modal-header">
    <h5 class="modal-title" id="staticBackdropLabel"><i class="bi bi-person-plus-fill"></i>&nbsp; New employee</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <div class="alert alert-danger d-none" id="feedbackArea" role="alert">
        A simple danger alert—check it out!
    </div>
    <form method='POST' id='createEmployee'>
        @csrf

        @isset($employee->id)
            <input type="hidden" name="id" value="{{ $employee->id}}">
        @endisset

        <div class="row">
            <div class="mb-3 col-6">
                <label for="name" class="form-label">First Name</label>
                <input type="text" name="first_name" value="{{ $employee->first_name ?? '' }}"
                       class="form-control text-uppercase" id="first_name" required
                       max="20" pattern="[A-Za-z]{1,20}">
            </div>
            <div class="mb-3 col-6">
                <label for="email" class="form-label">Other name</label>
                <input type="text" name="other_name" value="{{ $employee->first_name ?? '' }}"
                       class="form-control text-uppercase" id="other_name"
                       max="50" pattern="[a-zA-Z\s]{1,50}">
            </div>
        </div>

        <div class="row">
            <div class="mb-3 col-6">
                <label for="document" class="form-label">Middle name</label>
                <input type="text" name="middle_name" value="{{ $employee->middle_name ?? '' }}"
                       class="form-control text-uppercase" id="middle_name" required
                       max="20" pattern="[A-Za-z]{1,20}">
            </div>
            <div class="mb-3 col-6">
                <label for="phone" class="form-label">Last name</label>
                <input type="tel" name="last_name" value="{{ $employee->last_name ?? '' }}"
                       class="form-control text-uppercase" id="last_name" required max="20"
                       pattern="[A-Za-z]{1,20}">
            </div>
        </div>

        <div class="row">
            <div class="mb-3 col-6">
                <label for="address" class="form-label">Document type</label>
                <select name="document_type" class="form-select" id="document_type" required>
                    <option
                        value="Cédula de Ciudadanía" {{ (isset($employee->document_type) && $employee->document_type == 'Cédula de Ciudadanía') ? 'selected' : '' }}>
                        Cédula de Ciudadanía
                    </option>
                    <option
                        value="Cédula de Extranjería" {{ (isset($employee->document_type) && $employee->document_type == 'Cédula de Extranjería') ? 'selected' : '' }}>
                        Cédula de Extranjería
                    </option>
                    <option
                        value="Pasaporte" {{ (isset($employee->document_type) && $employee->document_type == 'Pasaporte') ? 'selected' : '' }}>
                        Pasaporte
                    </option>
                    <option
                        value="Permiso Especial" {{ (isset($employee->document_type) && $employee->document_type == 'Permiso Especial') ? 'selected' : '' }}>
                        Permiso Especial
                    </option>
                </select>
            </div>
            <div class="mb-3 col-6">
                <label for="address" class="form-label">Document number</label>
                <input type="text" name="document_number" value="{{ $employee->document_number ?? '' }}"
                       class="form-control" id="document_number" required
                       pattern="[a-zA-Z0-9-]*">
            </div>
        </div>

        <div class="row">
            <div class="mb-3 col-4">
                <label for="company" class="form-label">Work country</label>
                <select name="work_country" class="form-select" id="work_country" required>
                    <option
                        value="Colombia" {{ (isset($employee->work_country) && $employee->work_country == 'Colombia') ? 'selected' : '' }}>
                        Colombia
                    </option>
                    <option
                        value="Estados Unidos" {{ (isset($employee->work_country) && $employee->work_country == 'Estados Unidos') ? 'selected' : '' }}>
                        Estados Unidos
                    </option>
                </select>
            </div>
            <div class="mb-3 col-4">
                <label for="department" class="form-label">Department</label>
                <select name="department" class="form-select" id="department" required>
                    <option
                        value="Administración" {{ (isset($employee->department) && $employee->department == 'Administración') ? 'selected' : '' }}>
                        Administración
                    </option>
                    <option
                        value="Financiera" {{ (isset($employee->department) && $employee->department == 'Financiera') ? 'selected' : '' }}>
                        Financiera
                    </option>
                    <option
                        value="Compras" {{ (isset($employee->department) && $employee->department == 'Compras') ? 'selected' : '' }}>
                        Compras
                    </option>
                    <option
                        value="Infraestructura" {{ (isset($employee->department) && $employee->department == 'Infraestructura') ? 'selected' : '' }}>
                        Infraestructura
                    </option>
                    <option
                        value="Talento Humano" {{ (isset($employee->department) && $employee->department == 'Talento Humano') ? 'selected' : '' }}>
                        Talento Humano
                    </option>
                    <option
                        value="Servicios Varios" {{ (isset($employee->department) && $employee->department == 'Servicios Varios') ? 'selected' : '' }}>
                        Servicios Varios
                    </option>
                </select>
            </div>

            <div class="mb-3 col-4">
                <label for="start_date" class="form-label">Start date</label>
                <input type="date" id="start_date" class="form-control" name="start_date"
                       value="{{ $employee->start_date ?? '' }}" {{ isset($employee->start_date) ? 'readonly' : ''}}
                       min="{!! oneMonthAgo() !!}" max="{!! getToday() !!}">
            </div>

        </div>

        {{--Time stamps and mail address--}}
        @isset($employee->id)
            <div class="row">
                <div class="mb-3 col-4">
                    <label for="email" class="form-label">E-mail</label>
                    <input type="email" id="email" class="form-control" name="email"
                           value="{{ $employee->email ?? '' }}" readonly disabled>
                </div>
                <div class="mb-3 col-4">
                    <label for="updated_at" class="form-label">Updated at</label>
                    <input type="text" id="updated_at" class="form-control" name="updated_at"
                           value="{{ $employee->updated_at->format('d/m/Y H:i:s') ?? '' }}" readonly disabled>
                </div>
                <div class="mb-3 col-4">
                    <label for="created_at" class="form-label">Created at</label>
                    <input type="text" id="updated_at" class="form-control" name="created_at"
                           value="{{ $employee->created_at->format('d/m/Y H:i:s') ?? '' }}" readonly disabled>
                </div>
            </div>
        @endisset

        <div class="modal-footer pb-0 mt-3 pe-0">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x-circle-fill"></i>&nbsp; {{ __('general.close') }}
            </button>
            <button type="submit" class="btn btn-success" id="sendButton"><i
                    class="bi bi-sd-card-fill"></i>&nbsp; {{ __('general.save') }}</button>
        </div>
    </form>
</div>
<script>
    $("#createEmployee").on("submit", function (event) {
        event.preventDefault();
        event.stopPropagation();

        let sendButton = $("#sendButton");
        let sendButtonText = sendButton.text();
        let feedbackArea = $("#feedbackArea");

        if (this.checkValidity()) {
            const formValues = $(this).serialize();
            const route = "{!! isset($employee->id) ? route('employees.update', [$employee->id]) : route('employees.store') !!}"
            $.ajax({
                url: route,
                method: '{!! isset($employee->id) ? 'PUT' : 'POST' !!}',
                data: formValues,
                dataType: 'json',
                beforeSend: () => {
                    //Hide previously error message
                    feedbackArea.addClass("d-none");
                    $(".invalid-feedback").fadeOut();
                    $("input").removeClass("is-invalid");

                    // Prevent button from changing width
                    let sendButtonWidth = sendButton.outerWidth();
                    sendButton.css("min-width", sendButtonWidth + "px");

                    // Add spìnner
                    sendButton.html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> <span class="visually-hidden">Loading...</span>');
                },
                success: (data, textStatus, xhr) => {
                    if (data.success == true && xhr.status == 200) {
                        sendButton.html('<i class="bi bi-check-lg"></i>&nbsp; Saved');
                        feedbackArea.removeClass("alert-danger");
                        feedbackArea.removeClass("d-none");
                        feedbackArea.addClass("alert-success");
                        feedbackArea.fadeIn();
                        feedbackArea.html('The data was correctly saved.');
                        $('#employeesTable').DataTable().ajax.reload();
                        setTimeout(function () {
                            $("#modalWrapper").delay(2500).modal('hide');
                        }, 1800);
                    } else {
                        sendButton.html(sendButtonText);
                        feedbackArea.removeClass("d-none");
                        feedbackArea.fadeIn();
                        feedbackArea.html('');
                    }
                },
                error: (data, textStatus, xhr) => {
                    sendButton.html(sendButtonText);
                    feedbackArea.removeClass("d-none");
                    let errorMessage = ""
                    if (data.status == 422) {
                        let errorList = data.responseJSON.errors;
                        for (const [key, value] of Object.entries(errorList)) {
                            let element = $("input[name=" + key + "]");
                            console.log(element);
                            element.addClass('is-invalid');
                            element.after('<div class="invalid-feedback">' + value + '</div>');
                        }
                        errorMessage = "Invalid data. Review the submited data and try again.";
                    } else {
                        errorMessage = "An error has occurred. Please try again.";
                    }
                    feedbackArea.html(errorMessage);
                },
            })
        }
    });
</script>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Cidenet</title>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
            crossorigin="anonymous"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>
</head>

<body class="sb-nav-fixed sb-sidenav-toggled">
<div id="app">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Cidenet</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
                class="fas fa-bars"></i></button>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="{!! route('employees.index') !!}">
                            <div class="sb-nav-link-icon"><i class="bi bi-person-badge-fill"></i></div>
                            Employees
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Ezequias Lopes
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <nav style="--bs-breadcrumb-divider: '>';" class="mt-3" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">{{ __('general.home') }}</a></li>
                            <li class="breadcrumb-item active"
                                aria-current="page">Employees
                            </li>
                        </ol>
                    </nav>
                    @if(session()->get('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session()->get('success') }}
                        </div>
                    @endif
                    <div>
                        @yield('content')
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Ezequias Lopes</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
            @include('layouts.modal')
        </div>
    </div>
</div>
</body>

</html>

resources/views/layouts/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="modalWrapper" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
     aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg modal-fullscreen-md-down">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel"><i class="bi bi-hdd-network"></i>&nbsp; {{ __('general.loading') }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{{ __('general.close') }}"></button>
            </div>
            <div class="modal-body d-flex align-items-center justify-content-center" style="min-height: 75vh;">
                <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
                    <span class="visually-hidden">{{ __('general.loading') }}</span>
                </div>
            </div>
        </div>
    </div>
</div>